name: fastrl
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python=3.6
  - pip
  - cuda100
  - fastprogress
  - fastai=1.0.58
  - jupyter
  - notebook
  - setuptools
  - pip:
      - pytest
      - nvidia-ml-py3
      - dataclasses
      - numpy==1.17.4
      - pandas
      - pyyaml
      - opencv-contrib-python
      - requests
      - sklearn
      - cython
      - gym[box2d, atari]
      - easydict
      - matplotlib
      - jupyter_console
      - moviepy